### ISSUE TITLE
Nested patches are not being applied

### ISSUE THREAD

**Issue by mhawwari** [Vardot/composer-patches#2]
After updating to 1.7.5, the library is only applying patches inside the main composer.json and none of the patches in installed packages. Also, changes to patches weren't being detected without removing composer.local and composer/installed.json and running composer install.

**Comment by Natshah** [comment]
Aha , Thank you Hawwari for reporting and following up <3

[vardot/composer-patches](https://github.com/vardot/composer-patches)
It is a tag for **vardot/composer-patches** , which is a fork of require **cweagans/composer-patches**
**Added composer & io to dispatched events, along with on patch fails event  #243**
https://github.com/cweagans/composer-patches/pull/243

https://github.com/Vardot/composer-patches/releases/tag/1.7.5 , I released it

In Varbase composer
```
  "repositories": {
    "drupal": {
      "type": "composer",
      "url": "https://packages.drupal.org/8"
      },
    "assets": {
      "type": "composer",
      "url": "https://asset-packagist.org"
    },
    "composer-patches": {
      "type": "vcs",
      "url": "https://github.com/vardot/composer-patches"
    }
  },
```

I have noticed your fix on "cweagans/composer-patches": "1.7.0",
That means we could fix our **vardot/composer-patches** to work well after the last merge ..
We have to fix the issue after the merge in Composer ~1.0 and Composer ~2.0
 then release 1.7.6
